main_app/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    #  Record Model Related Paths 
    path('records/', views.RecordList.as_view(), name='records_index'),
    path('records/<int:pk>/', views.RecordDetail.as_view(), name='records_detail'),
    path('records/create/', views.RecordCreate.as_view(), name='records_create'),
    path('records/<int:pk>/update', views.RecordUpdate.as_view(), name='records_update'),
    path('records/<int:pk>/delete', views.RecordDelete.as_view(), name='records_delete'),

    # Crate Model Related Paths
    path('crates/<int:pk>/', views.CrateDetail.as_view(), name='crates_detail'),
    path('crates/create/', views.CrateCreate.as_view(), name='crates_create'),
    path('crates/<int:pk>/update', views.CrateUpdate.as_view(), name='crates_update'),
    path('crates/get_crate', views.get_crate, name='get_crate'),

    # Path for user profile
    # path('')
    path('users/', views.UserList.as_view(), name='users'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='users_detail'),
    path('users/<int:pk>/update', views.UserUpdate.as_view(), name='users_update'),
    path('users/<int:pk>/delete', views.UserDelete.as_view(), name='users_delete'),


    # path('oldUser/', views.user, name='oldUser'),
   


    # Associate & Un-associate a record with a Crate
    path('records/<int:record_id>/assoc_record/', views.assoc_record, name='assoc_record'),
    path('crates/<int:pk>/unassoc_record/<int:record_id>/', views.unassoc_record, name='unassoc_record'),


    # # Add Track List
    path('records/<int:pk>/add_tracklist/', views.add_tracklist, name='add_tracklist'),


    # Artists Display All
    path('artists/', views.ArtistList.as_view(), name='artists_index'),
    # # Artist Display Detail 
    path('artists/<int:pk>/', views.ArtistDetail.as_view(), name = 'artists_detail'),
    # # Artist Creation 
    path('artists/create', views.ArtistCreate.as_view(), name = 'artists_create'),
    # # Artist Update
    path('artists/<int:pk>/update', views.ArtistUpdate.as_view(), name = 'artists_update'),
    # # Artist Delete
    path('artists/<int:pk>/delete', views.ArtistDelete.as_view(), name = 'artists_delete'),



    # Associate and Unassociate an Artist with a Record (M:M)
    path('records/<int:record_id>/assoc_artist/<int:artist_id>/', views.assoc_artist, name='assoc_artist'),
    path('records/<int:record_id>/unassoc_artist/<int:artist_id>/', views.unassoc_artist, name='unassoc_artist'),



    # Signup Route/URL
    path('accounts/signup/', views.signup, name='signup'),

    path("password_reset/", views.password_reset_request, name="new_password_reset"),


]

urlpatterns += staticfiles_urlpatterns()

thephonograph/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views





urlpatterns = [
    path('admin/', admin.site.urls),
    # Mounting Routes
    path('', include('main_app.urls')),
    # Mounting on account route for auth
    path('accounts/', include('django.contrib.auth.urls')),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main_app/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main_app/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main_app/password/password_reset_complete.html'), name='password_reset_complete'),
]

main_app/models.py
from cProfile import label
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from pkg_resources import require


# Create your models here.
class Artist(models.Model):
    artist_name = models.CharField(max_length=100)
    artist_age = models.IntegerField("Artist Age")
    artist_location = models.CharField(max_length=100)
    image = models.URLField(max_length=1000, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.artist_name

    def get_absolute_url(self):
        return reverse('artists_detail', kwargs={"pk": self.id})


class Record(models.Model):
    name = models.CharField(max_length=100)
    label = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    description  = models.TextField(max_length=1000)
    format = models.CharField(max_length=50)
    release_date = models.DateField()
    image = models.URLField(max_length=1000)
    image_two = models.URLField(max_length=1000, blank=True, null=True)
    artists = models.ManyToManyField(Artist)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('records_detail', kwargs={"pk": self.id})


class Crate(models.Model):
    name = models.CharField(max_length=100)
    records = models.ManyToManyField(Record)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('crates_detail', kwargs = {'pk': self.id})


class Tracklist(models.Model):
    track_name = models.CharField(max_length=100)
    track_duration = models.FloatField()
    record = models.ForeignKey(Record, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.track_name

main_app/forms.py
from django.forms import ModelForm
from .models import Tracklist, Artist
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse




    

class TracklistForm(forms.ModelForm):

    class Meta:
        model = Tracklist
        fields = ['track_name', 'track_duration']

# New User Form here (this allows the user to input email, first and last name as well when signing up)
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

    def get_absolute_url(self):
        return reverse('users', kwargs = {'pk': self.id})

  

main_app/views.py
from ast import For
from django.shortcuts import render, redirect

from .forms import NewUserForm, TracklistForm
from .models import Artist, Record, Crate

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .forms import TracklistForm
# User Auth Imports
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os

from django.urls import reverse
# Imports for Messages
from django.contrib import messages

# Imports for Password Reset
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
  


def home(request):
    crateInfo = Crate.objects.all()
    return render(request, 'home.html', {'crateInfo': crateInfo})

def about(request):
    return render(request, 'about.html')

class UserList(ListView):
    model = User

class UserDetail(DetailView):
    model = User

class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'username']

class UserDelete(LoginRequiredMixin, DeleteView):
    model = User 
    success_url = '/'
    success_message = "You have been deleted from the database."


class ArtistList(ListView):
    model = Artist

class ArtistDetail(DetailView):
    model = Artist

class ArtistCreate(LoginRequiredMixin, CreateView):
    model = Artist
    fields = '__all__'

    def form_valid(self, form):
        form.instance.user = self.request.user
        # instead of request, "Success message" it is self.request, "success etc"
        messages.success(self.request, "You have added a Artist to the database!" )
        return super().form_valid(form)



    

class ArtistUpdate(LoginRequiredMixin, UpdateView):
    model = Artist 
    fields = ['artist_name','artist_age','artist_location','image']
    
    def form_valid(self, form):
        
        form.instance.user = self.request.user
        messages.success(self.request, "You have successfully updated the Artist!" )
        return super().form_valid(form)



class ArtistDelete(LoginRequiredMixin, DeleteView):
    model = Artist   
    success_url = '/artists/'
    success_message = "You have successfully removed a Artist from the database!"
   
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ArtistDelete, self).delete(request, *args, **kwargs)


    

class RecordList(ListView):
    model = Record

class RecordDetail(DetailView):
    model = Record
    
    def get_context_data(self, **kwargs):
        context = super(RecordDetail, self).get_context_data(**kwargs)
        context['form'] = TracklistForm()
        return context

class RecordCreate(LoginRequiredMixin, CreateView):
    model = Record 
    fields = '__all__'
    success_url = '/records/'
    
    

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "You have added a Record to the database!" )
        return super().form_valid(form)


class RecordUpdate(LoginRequiredMixin, UpdateView):
    model = Record
    fields = '__all__'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "You have successfully updated the Record!" )
        return super().form_valid(form)    


class RecordDelete(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = '/records/'
    success_message = "You have successfully removed a Record from the database!"
   
    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(RecordDelete, self).delete(request, *args, **kwargs)


@login_required
def add_tracklist(request, pk):
    form = TracklistForm(request.POST)

    if form.is_valid():
        new_tracklist = form.save(commit=False)
        new_tracklist.record_id = pk
        new_tracklist.save()
        return redirect('records_detail', pk = pk)

# Crate Views
class CrateDetail(LoginRequiredMixin, DetailView):
    model = Crate


class CrateCreate(LoginRequiredMixin, CreateView):
    model = Crate
    fields = ['name', 'records']

class CrateUpdate(LoginRequiredMixin, UpdateView):
    model = Crate
    fields = ['name', 'records']

@login_required
def get_crate(request):
    pk = request.user.id
    return redirect('crates_detail', pk=pk)

def user(request):
    pk = request.user.id
    return redirect('user', pk=pk)


# Associate & Un-associate a record with a Crate
@login_required
def assoc_record(request, record_id):
    pk = request.user.id 
    Crate.objects.get(id=pk).records.add(record_id)
    return redirect('crates_detail', pk=pk)

@login_required
def unassoc_record(request, pk, record_id):
    Crate.objects.get(id=pk).records.remove(record_id)
    return redirect('crates_detail', pk=pk)


def signup(request):
    error_message = ''

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "You have successfully signed up!" )
            return redirect('records_index')
        else:
            messages.error(request, "Your signup has not been successful, please try again." )
            return redirect('signup')
        

    form = NewUserForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)



@login_required
def assoc_artist(request, record_id, artist_id):
    # First select object then add a toy 
    Record.objects.get(id=record_id).artist.add(artist_id)
    return redirect('detail', record_id = record_id)
@login_required
def unassoc_artist(request, record_id, artist_id):
    # Remove link from join table 
    Record.objects.get(id=record_id).artist.remove(artist_id)
    return redirect('detail', record_id = record_id)


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "main_app/password/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:9000',
					'site_name': 'The Phonograph',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="main_app/password/password_reset.html", context={"password_reset_form":password_reset_form})



# NOT WORKING
# class AdminLogin(LoginView):
#     template_name = 'login.html'

#     def form_valid(self, form):
#         messages.success(self.request, "You have logged in")
#         return super().form_valid(form)  
    

main_app/templates/main_app/artist_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Artist</h1>


<h4> Are you sure you want to delete 
    <span>{{ object.name }}</span>?
</h4>

<form action="" method="post">

    {% csrf_token %}

    <input type="submit" value="Yes - Delete!!!">
    <a href="{% url 'artists_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/artist_detail.html
{% extends 'base.html' %} {% block content %}

<div class="grid grid-cols-2 artist-info-container">
  <div class="aspect-auto image-details-container pl-2 pt-2">
    <img class="image-details-page" src="{{artist.image}}" />
  </div>

  <div class="artist-details-container pr-2">
    <span class="artist-text"> Artist(s): {{ artist.artist_name }} </span>
    <br />
    <hr />
    <span>Age: {{ artist.artist_age }}</span>
    <br />
    <hr />
    <span>Location: {{ artist.artist_location }}</span>

    <br />
    <div class="mt-3">
      <a
        class="bg-blue-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-yellow-700 hover: border-amber-400 rounded"
        style="background-color: #524f4a"
        href="{% url 'artists_update' artist.id %}"
        >Edit</a
      >
      <a
        class="bg-blue-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-yellow-700 hover: border-amber-400 rounded"
        style="background-color: #524f4a"
        href="{% url 'artists_delete' artist.id %}"
        >Delete</a
      >
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/artist_form.html
{% extends 'base.html'%}

{% block content %}




<div class="form-container">

    <form class="artist-form" action="" method="post" onSubmit="clearField();">


        {% csrf_token %}

        <table>

            {% if object %}
                <h1>Edit <span>{{ object.name }}</span></h1>
            {% else%}
                <h1>Add Artist</h1>
            {% endif %}


            {{form.as_table}}
            
        </table>

        <input type="submit" value="Submit" class=" ">

    </form>



    {% endblock %}

</div>

main_app/templates/main_app/artist_list.html
{% extends 'base.html' %}

{% block content %}



<div class="flex flex-wrap justify-center">


    {% for artist in artist_list %}

        <div class="h-25 w-25 ml-3 mr-3 mt-3 mb-3" style="background-color: white">


            <a href="{% url 'artists_detail' artist.id%}"><img src="{{artist.image}}" class="aspect-auto"></a>
            
            <div class="container pt-2 h-20 items-center justify-items-center">

                <span class="artist-name block">{{ artist.artist_name }}</span>
                
                <span class="artist-location block">{{ artist.artist_location }}</span>

            </div>
        </div>

    </a>

    {% endfor %}

</div>
{% endblock %}

main_app/templates/main_app/crate_detail.html
{% extends 'base.html' %} {% block content %}

<div class="flex justify-center mb-3 mt-3">

  <h1 class="record-name">{{ crate.name }}</h1>
</div>


{% for record in crate.records.all %}

<div class="record-container flex wrap ml-3 mr-3 mt-3 border-2 border-black justify-between" style="background-color: white;">
  <div class="flex wrap">
<div class="mt-1 ml-1 mb-1 mr-1"> <a href="{% url 'records_detail' record.id %}"><img class="h-44" src="{{record.image}}" alt=""></a> </div>

  <div class="mt-1 ml-3 w-96"> 
    Name: <span class="record-name">{{ record.name }}</span> 
    Genre: <br> <span class="record-name">{{ record.genre }}</span> 
    Artist(s): <br> <span class="record-name"> {% for artist in record.artists.all %}

        {{artist.artist_name}}
    
        {% endfor %} </span>
  </div>
</div>
  <div class="self-end mr-1 mb-1">
    <form action="{% url 'unassoc_record' crate.id record.id %}" method="post">
      {% csrf_token %}
      
      <button class="text-white font-bold py-2 px-4 border-b-4 border-yellow-700 hover: border-amber-400 rounded" style="background-color: #524F4a;" type="submit">Remove</button>
    
    </form>
  </div>
</div>

{% endfor %} {% endblock %}

main_app/templates/main_app/crate_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span>{{ object.name }}</span></h1>
{% else%}
    <h1>Create Crate</h1>
{% endif %}

<form action="" method="post" onSubmit="clearField();">

    {% csrf_token %}

    <table>
        
        {{form.as_table}}
        
    </table>

    <input type="submit" value="submit">

</form>


{% endblock %}

main_app/templates/main_app/record_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Record</h1>


<h4> Are you sure you want to delete 
    <span>{{ object.name }}</span>?
</h4>

<form action="" method="post">

    {% csrf_token %}

    <input type="submit" value="Yes - Delete!!!" >
    <a href="{% url 'records_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/record_detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <form action="{% url 'assoc_record' record.id %}" method="post">
      {% csrf_token %}
      <button class=" ml-2 mt-2 bg-blue-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4  border-yellow-700 hover: border-amber-400 rounded" style="background-color: #524F4a" type="submit">Add to Crate</button>

    </form>

  </div>
<!-- flex justify-between -->
<div class="grid aspect-auto grid-cols-2 record-info-container" >
    <div class="aspect-auto image-details-container pl-2 pt-2">
        <img class="image-details-page" src={{record.image}} >
        {% if record.image_two %}
        <img class="pt-2 image-details-page" src={{record.image_two}} >
        {% endif %}

    </div>

    <div class="record-details-container pr-2 ">
        <span class="artist-text">Artist(s): {% for artist in record.artists.all %}

        {{artist.artist_name}}
    
        {% endfor %}
        </span> 
        <br>
        <hr>
        Name: {{ record.name }}  
        <br>
        <hr>
        Label: {{ record.label }}  
        <br>
        <hr>
        Genre: {{ record.genre }}   
        <br>
        <hr>
        Format: {{ record.format }}  
        <br>
        <hr>
        Release Date: {{ record.release_date }}
        <br>
        <hr>
        <br>
        <a class=" bg-blue-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4 border-yellow-700 hover: border-amber-400 rounded" style="background-color: #524F4a" href="{% url 'records_update' record.id %}">Edit Record Details</a>
        <a class=" bg-blue-500 hover:bg-red-400 text-white font-bold py-2 px-4 border-b-4  border-yellow-700 hover: border-amber-400 rounded" style="background-color: #524F4a" href="{% url 'records_delete' record.id %}">Delete Record</a>  
        
        <br>

        <div class="description">
            <br>
            <hr>
            Description: {{ record.description }}  
            <br>
            <hr>
        </div>

        <br>

        <div>

            <form action="{% url 'add_tracklist' record.id %}" method="post" onSubmit="clearField();">
        
        
                {% csrf_token %}
        
                {{ form.as_p }}
        
        
        
                
        
                <input class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" style="background-color: #524F4a" type="submit" value="Add Track">
        
        
            </form>
        
        
            <table>
        
                <thead>
        
        
                    <tr>
        
                        <th>Track Name</th>
                        <th>Track Duration</th>
                    </tr>
                </thead>
        
        
                <tbody>
                    {% for tracklist in record.tracklist_set.all %}
                    <tr>
                        <td>{{tracklist.track_name }}</td>
                        <td>{{tracklist.track_duration }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
        
        
            </table>
        
        
        </div>
    </div>  



</div>


{% endblock %}

main_app/templates/main_app/record_form.html
{% extends 'base.html' %}

{% block content %}




<div class="form-container">

    
    <form class="record-form" action="" method="post" onSubmit="clearField();">



        {% csrf_token %}

        <table>
            
            {% if object %}
    
                <h1>Edit <span>{{ object.name }}</span></h1>

            {% else%}

                <h1>Create Record</h1>
        
            {% endif %}

            
            {{form.as_table}}
            
        </table>

        <input class="" type="submit" value="Submit">

    </form>


    {% endblock %}

</div>

main_app/templates/main_app/record_list.html
{% extends 'base.html' %} 
{% block content %}

<div class="flex flex-wrap justify-center" style="background-color: #E5E3D7;">
{% for record in record_list %}

<div class=" thumbnail-container h-25 w-25 ml-3 mr-3 mt-3 mb-3">

  <a href="{% url 'records_detail' record.id %}"> <img src="{{ record.image }}" class="aspect-auto "></a>

  <div class="h-20 flex items-center justify-items-center" style="background-color: white;">
    <p class="ml-1 mr-1 mt-1 mb-1">
      
    <span class="record-name ">{{ record.name }}</span> 
    
    
    {% for artist in record.artists.all %}

    <span class="record-artist">{{artist.artist_name}}</span>

    {% endfor %}</p>



  </div>
</div>

{% endfor %} 
</div>

{% endblock %}

main_app/templates/main_app/users.html
{% extends 'base.html' %} {% block content %}

<div >

    working!!

</div>

{% endfor %} {% endblock %}